{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app-ingress
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize | default "40m" }}
    nginx.ingress.kubernetes.io/autoindex: "on"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: {{ .Values.ingress.proxyMaxTempFileSize | default "5m" }}
    nginx.ingress.kubernetes.io/add-header: X-Cache-Status $upstream_cache_status
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.backendProtocol | default "TCP" }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appname }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
